#!/bin/bash

#PBS -l nodes=10:ppn=12
#PBS -l walltime=0:01:00


#PBS -q batch
#PBS -N nQueensResult
#PBS -j oe

cd /home/razat/nQueens-MPI
mpiexec -np 10 --map-by ppr:1:node --hostfile $PBS_NODEFILE ./main.x
