#!/bin/bash

#PBS -l nodes=3:ppn=12
#PBS -l walltime=0:01:00


#PBS -q batch
#PBS -N NQueens
#PBS -j oe

cd /home/arrowoode/nQueens-MPI
mpiexec -np 3 --map-by ppr:1:node --hostfile $PBS_NODEFILE ./parallel.x
