#!/bin/bash

#PBS -l nodes=2:ppn=12
#PBS -l walltime=0:00:30


#PBS -q batch
#PBS -N NQueens
#PBS -j oe

cd /home/arrowoode/nQueens-MPI
mpiexec -np 2 --map-by ppr:1:node --hostfile $PBS_NODEFILE ./parallel.x
